openapi: 3.0.3
info:
    title: Key Stone
    description: Key Stone is a platform for managing your keys
    version: v0.0.1
servers:
    - url: http://localhost:80
      description: Default server for key-stone
paths:
    /key-stone/auth:
        post:
            tags:
                - token
            summary: issue token
            operationId: token#issue
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            user:
                                password: Dolores fuga asperiores voluptatem aspernatur eum.
                                username: Explicabo placeat.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TokenDetail'
                            example:
                                access_token: Sapiente temporibus vel.
                                expires_in: 5781008252414769887
                                refresh_token: Quo dolores.
                                token_type: Illo et rerum quia odit voluptas.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /key-stone/auth/refresh:
        post:
            tags:
                - token
            summary: refresh token
            operationId: token#refresh
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RefreshRequestBody'
                        example:
                            token:
                                access_token: Et quia illum.
                                refresh_token: Distinctio quam sunt est sed alias.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TokenDetail'
                            example:
                                access_token: Mollitia ab delectus.
                                expires_in: 7288946790282810514
                                refresh_token: Fugiat quos.
                                token_type: Inventore ducimus laboriosam exercitationem eos voluptatem.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'InternalServerError: Internal Server Error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /key-stone/users:
        post:
            tags:
                - user
            summary: create user
            operationId: user#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            user:
                                password: Occaecati vel adipisci.
                                username: Quia architecto veritatis deleniti ea perferendis.
            responses:
                "204":
                    description: No Content response.
    /key-stone/users/me:
        delete:
            tags:
                - user
            summary: delete user
            operationId: user#delete
            responses:
                "204":
                    description: No Content response.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        CreateRequestBody:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/UserInput'
            example:
                user:
                    password: Occaecati vel adipisci.
                    username: Quia architecto veritatis deleniti ea perferendis.
            required:
                - user
        DeleteUserPayload:
            type: object
            properties:
                Authorization:
                    type: string
                    description: The payload of the user
                    example: Consequuntur quibusdam nihil vel.
            example:
                Authorization: Dolor ut tempore.
            required:
                - Authorization
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: Unauthorized
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        IssueInput:
            type: object
            properties:
                password:
                    type: string
                    description: The password of the user
                    example: Dolorum tempora et consequatur nam atque.
                username:
                    type: string
                    description: The username of the user
                    example: Odit aspernatur.
            example:
                password: Qui harum sit ex ut.
                username: Quos sed facilis reprehenderit velit aliquam.
            required:
                - username
                - password
        RefreshInput:
            type: object
            properties:
                access_token:
                    type: string
                    description: The access token of the user
                    example: Rerum dolores omnis.
                refresh_token:
                    type: string
                    description: The refresh token of the user
                    example: Quo asperiores aliquam ducimus.
            example:
                access_token: Illo molestiae reprehenderit et eveniet.
                refresh_token: Laboriosam nobis minus voluptatem.
            required:
                - access_token
                - refresh_token
        RefreshRequestBody:
            type: object
            properties:
                token:
                    $ref: '#/components/schemas/RefreshInput'
            example:
                token:
                    access_token: Et quia illum.
                    refresh_token: Distinctio quam sunt est sed alias.
            required:
                - token
        TokenDetail:
            type: object
            properties:
                access_token:
                    type: string
                    description: The access token of the user
                    example: Quia mollitia consectetur enim.
                expires_in:
                    type: integer
                    description: The expires in of the user
                    example: 8566094199576836059
                    format: int64
                refresh_token:
                    type: string
                    description: The refresh token of the user
                    example: Qui et omnis.
                token_type:
                    type: string
                    description: The token type of the user
                    example: Nulla dolor recusandae illo.
            example:
                access_token: Molestiae cumque ut facere.
                expires_in: 2950528847670145197
                refresh_token: Cumque et hic omnis non rerum.
                token_type: Reiciendis dolor et veniam sapiente fugiat.
            required:
                - access_token
                - token_type
                - expires_in
                - refresh_token
        UserInput:
            type: object
            properties:
                password:
                    type: string
                    description: The password of the user
                    example: Ex asperiores rerum possimus qui numquam.
                username:
                    type: string
                    description: The name of the user
                    example: Eaque tempora non tenetur.
            example:
                password: In sint.
                username: Officiis ea ipsa qui.
            required:
                - username
                - password
tags:
    - name: user
    - name: token
